Config = {}

-- Time in seconds between backup requests per player
Config.Cooldown = 3

-- Time in milliseconds to show the NUI notification on screen
Config.DisplayTime = 8000

-- Restriction settings (only police can send/receive backups)
Config.PoliceOnly = true

-- Server side check to determine if a player is police
-- Returns true if police, false otherwise
if IsDuplicityVersion() then
    Config.IsPlayerPolice = function(source)
        if not Config.PoliceOnly then return true end
        
        if GetResourceState('police_armory') == 'started' then
            local job = exports.police_armory:GetPoliceJob(source)
            return job ~= nil
        end
        
        -- Fallback: if police_armory is not started, allow all for debugging/testing
        return true
    end
else
    -- Client side check
    Config.IsPlayerPoliceLocal = function()
        if not Config.PoliceOnly then return true end
        return true
    end
end

-- Configuration for each backup level (1 to 5)
-- Blip Colors in GTA V:
-- 1: Red (Roșu)
-- 5: Yellow (Galben)
-- 17: Orange (Portocaliu)
-- 3: Blue (Albastru)
-- 39: Grey/Silver (Gri)
Config.BackupLevels = {
    [1] = {
        name = "BK 1",
        label = "COD ROSU - OFITER IN PERICOL - SPRIJIN DE URGENTA",
        colorHex = "#E63946", -- Red
        colorRgb = "230, 57, 70",
        blipColor = 1,
        blipSprite = 161,
        blipScale = 1.3,
        flashBlip = true,
        route = true,
        urgency = "high"
    },
    [2] = {
        name = "BK 2",
        label = "SOLICITARE INTARIRI - DEPLASARE CU GIROFARE",
        colorHex = "#FFD166", -- Yellow
        colorRgb = "255, 209, 102",
        blipColor = 5,
        blipSprite = 161,
        blipScale = 1.1,
        flashBlip = false,
        route = true,
        urgency = "medium"
    },
    [3] = {
        name = "BK 3",
        label = "URGENTA - DEPLASARE CU SIRENE SI GIROFARE",
        colorHex = "#F39C12", -- Orange
        colorRgb = "243, 156, 18",
        blipColor = 17,
        blipSprite = 161,
        blipScale = 1.1,
        flashBlip = false,
        route = true,
        urgency = "medium"
    },
    [4] = {
        name = "BK 4",
        label = "SPRIJIN RUTINAR - COD 2 DEPLASARE",
        colorHex = "#3B82F6", -- Blue
        colorRgb = "59, 130, 246",
        blipColor = 3,
        blipSprite = 161,
        blipScale = 1.0,
        flashBlip = false,
        route = true,
        urgency = "low"
    },
    [5] = {
        name = "BK 5",
        label = "SOLICITARE ASISTENTA - COD 1 DEPLASARE",
        colorHex = "#A0AAB0", -- Grey
        colorRgb = "160, 170, 176",
        blipColor = 39,
        blipSprite = 161,
        blipScale = 1.0,
        flashBlip = false,
        route = true,
        urgency = "low"
    }
}

-- Gunshot Dispatch Alerts Configuration
Config.GunshotAlerts = true

-- Cooldown in milliseconds between gunshot alerts generated by the same client
Config.GunshotCooldown = 3000

-- Ignore gunshots fired by police officers (true) or report them too (false)
Config.IgnorePoliceShots = true

-- Map Blip configurations for gunshots
Config.GunshotBlipColor = 1 -- Red
Config.GunshotBlipRadius = 120.0 -- Radius of the red radar circle in meters
Config.GunshotBlipDuration = 20.0 -- Fade out duration in seconds

-- Blacklist of weapon hashes that should NOT trigger gunshot alerts (tasers, flareguns, ext., etc.)
Config.GunshotBlacklist = {
    [GetHashKey("WEAPON_STUNGUN")] = true,
    [GetHashKey("WEAPON_FLARE")] = true,
    [GetHashKey("WEAPON_FLAREGUN")] = true,
    [GetHashKey("WEAPON_FIREEXTINGUISHER")] = true,
    [GetHashKey("WEAPON_PETROLCAN")] = true,
    [GetHashKey("WEAPON_SNOWBALL")] = true,
    [GetHashKey("WEAPON_BALL")] = true,
    [GetHashKey("WEAPON_HAZARDCAN")] = true,
    [GetHashKey("WEAPON_FERTILIZERCAN")] = true
}

